"""create video production models

Revision ID: 826caac742dc
Revises:
Create Date: 2026-08-04 15:12:10.791653
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "826caac742dc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trends",
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trends")),
    )
    op.create_index(op.f("ix_trends_observed_at"), "trends", ["observed_at"], unique=False)
    op.create_index(op.f("ix_trends_source"), "trends", ["source"], unique=False)
    op.create_table(
        "topics",
        sa.Column("trend_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trend_id"], ["trends.id"], name=op.f("fk_topics_trend_id_trends"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
    )
    op.create_index(op.f("ix_topics_trend_id"), "topics", ["trend_id"], unique=False)
    op.create_table(
        "video_projects",
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "RESEARCHING",
                "SCRIPT_GENERATING",
                "SCRIPT_READY",
                "AUDIO_GENERATING",
                "ASSETS_GENERATING",
                "RENDERING",
                "REVIEW_REQUIRED",
                "APPROVED",
                "PUBLISHING",
                "PUBLISHED",
                "FAILED",
                name="videoprojectstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_video_projects_topic_id_topics"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_projects")),
    )
    op.create_index(op.f("ix_video_projects_status"), "video_projects", ["status"], unique=False)
    op.create_index(
        op.f("ix_video_projects_topic_id"), "video_projects", ["topic_id"], unique=False
    )
    op.create_table(
        "publications",
        sa.Column("video_project_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_project_id"],
            ["video_projects.id"],
            name=op.f("fk_publications_video_project_id_video_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint("platform", "external_id", name="platform_external_id"),
    )
    op.create_index(
        op.f("ix_publications_published_at"), "publications", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_publications_video_project_id"), "publications", ["video_project_id"], unique=False
    )
    op.create_table(
        "video_scenes",
        sa.Column("video_project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("visual_description", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_project_id"],
            ["video_projects.id"],
            name=op.f("fk_video_scenes_video_project_id_video_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_scenes")),
        sa.UniqueConstraint("video_project_id", "position", name="scene_position"),
    )
    op.create_index(
        op.f("ix_video_scenes_video_project_id"), "video_scenes", ["video_project_id"], unique=False
    )
    op.create_table(
        "media_assets",
        sa.Column("video_project_id", sa.Uuid(), nullable=False),
        sa.Column("video_scene_id", sa.Uuid(), nullable=True),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("uri", sa.String(length=2048), nullable=False),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_project_id"],
            ["video_projects.id"],
            name=op.f("fk_media_assets_video_project_id_video_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_scene_id"],
            ["video_scenes.id"],
            name=op.f("fk_media_assets_video_scene_id_video_scenes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        op.f("ix_media_assets_asset_type"), "media_assets", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_video_project_id"), "media_assets", ["video_project_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_video_scene_id"), "media_assets", ["video_scene_id"], unique=False
    )
    op.create_table(
        "metric_snapshots",
        sa.Column("publication_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_metric_snapshots_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_snapshots")),
        sa.UniqueConstraint("publication_id", "captured_at", name="publication_captured_at"),
    )
    op.create_index(
        op.f("ix_metric_snapshots_captured_at"), "metric_snapshots", ["captured_at"], unique=False
    )
    op.create_index(
        op.f("ix_metric_snapshots_publication_id"),
        "metric_snapshots",
        ["publication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metric_snapshots_publication_id"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_captured_at"), table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
    op.drop_index(op.f("ix_media_assets_video_scene_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_video_project_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_asset_type"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_video_scenes_video_project_id"), table_name="video_scenes")
    op.drop_table("video_scenes")
    op.drop_index(op.f("ix_publications_video_project_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_published_at"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(op.f("ix_video_projects_topic_id"), table_name="video_projects")
    op.drop_index(op.f("ix_video_projects_status"), table_name="video_projects")
    op.drop_table("video_projects")
    op.drop_index(op.f("ix_topics_trend_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_trends_source"), table_name="trends")
    op.drop_index(op.f("ix_trends_observed_at"), table_name="trends")
    op.drop_table("trends")
    # ### end Alembic commands ###
