"""add video project creation fields

Revision ID: 960dcf4ee41a
Revises: 826caac742dc
Create Date: 2026-08-05 12:01:24.237553
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "960dcf4ee41a"
down_revision: str | None = "826caac742dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_projects",
        sa.Column(
            "language", sa.String(length=20), server_default=sa.text("'pt-BR'"), nullable=False
        ),
    )
    op.add_column(
        "video_projects",
        sa.Column("duration_minutes", sa.Integer(), server_default=sa.text("5"), nullable=False),
    )
    op.add_column(
        "video_projects",
        sa.Column(
            "format", sa.String(length=50), server_default=sa.text("'faceless'"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video_projects", "format")
    op.drop_column("video_projects", "duration_minutes")
    op.drop_column("video_projects", "language")
    # ### end Alembic commands ###
